/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    careers: Career;
    'career-lifecycle': CareerLifecycle;
    organisations: Organisation;
    'event-lifecycle': EventLifecycle;
    users: User;
    media: Media;
    committee: Committee;
    sponsors: Sponsor;
    events: Event;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    careers: CareersSelect<false> | CareersSelect<true>;
    'career-lifecycle': CareerLifecycleSelect<false> | CareerLifecycleSelect<true>;
    organisations: OrganisationsSelect<false> | OrganisationsSelect<true>;
    'event-lifecycle': EventLifecycleSelect<false> | EventLifecycleSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    committee: CommitteeSelect<false> | CommitteeSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage opportunities for students. Save private drafts, review details and publish when ready. Rolling roles expire after 60 days; update the listed date after reconfirming availability.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  company: string;
  type?:
    | ('internship' | 'cadet' | 'graduate' | 'vacation' | 'part-time' | 'casual' | 'full-time' | 'volunteer' | 'other')
    | null;
  industry?: string | null;
  companyWebsite?: string | null;
  /**
   * Optional https:// image URL.
   */
  logoUrl?: string | null;
  /**
   * Australia, Malaysia, or both.
   */
  country?: string | null;
  /**
   * Use the state name or describe multiple locations.
   */
  state?: string | null;
  city?: string | null;
  workMode?: ('onsite' | 'hybrid' | 'remote') | null;
  international?: ('yes' | 'no' | 'unsure') | null;
  studyLevels?: ('any' | 'pre-penultimate' | 'penultimate' | 'final' | 'graduate' | 'postgraduate')[] | null;
  eligibility?: string | null;
  applyUrl: string;
  /**
   * YYYY-MM-DD. Leave empty for rolling applications.
   */
  closes?: string | null;
  /**
   * YYYY-MM-DD. Only update after reconfirming that a role is still available.
   */
  added?: string | null;
  /**
   * For example $35/hour, RM 4,800/month, or Not disclosed.
   */
  pay?: string | null;
  description?: string | null;
  /**
   * Optional tags separated by commas.
   */
  tags?: string | null;
  featured?: boolean | null;
  /**
   * Stable public link ID, generated automatically.
   */
  slug?: string | null;
  /**
   * Private to signed-in CMS users. Never shown on the website.
   */
  internalNotes?: string | null;
  sourceKey?: string | null;
  lifecycle?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-lifecycle".
 */
export interface CareerLifecycle {
  id: number;
  career: number | Career;
  status: string;
  closedAt?: string | null;
  archivedAt?: string | null;
  changedBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage the people who can sign in and update MASCA website content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Malaysian student organisations. Source listings are a starting point, not confirmation of current activity. Check and update names before use.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations".
 */
export interface Organisation {
  id: number;
  name: string;
  abbreviation?: string | null;
  university?: string | null;
  /**
   * State or territory abbreviation, or National.
   */
  state?: string | null;
  /**
   * Other names or abbreviations that should match a search.
   */
  aliases?: string | null;
  /**
   * Show in event organisation search. Turn off outdated entries.
   */
  listed?: boolean | null;
  sourceURL?: string | null;
  sourceCheckedAt?: string | null;
  verificationNotes?: string | null;
  directoryKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-lifecycle".
 */
export interface EventLifecycle {
  id: number;
  event: number | Event;
  status: string;
  completedAt?: string | null;
  archivedAt?: string | null;
  changedBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Add events for MASCA students and review submissions before they appear on the website. An event appears publicly only after it is approved and published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  lifecycle?: string | null;
  title: string;
  organisation: string;
  description: string;
  startDate: string;
  endDate?: string | null;
  /**
   * The name of the place, such as Great Court, University of Queensland. For an online event, enter Online.
   */
  venue: string;
  /**
   * Street number and name, suburb and postcode. Leave blank for online events.
   */
  streetAddress?: string | null;
  /**
   * Optional details for attendees: room, floor, entrance, meeting point or accessibility instructions.
   */
  venueDetails?: string | null;
  state: 'VIC' | 'NSW' | 'QLD' | 'WA' | 'SA' | 'TAS' | 'ACT' | 'NT';
  /**
   * Optional. Use a full https:// link for tickets or event details.
   */
  ticketURL?: string | null;
  /**
   * Choose an existing poster or upload an image up to 5 MB. This is the image students will see.
   */
  poster?: (number | null) | Media;
  contactName: string;
  contactEmail: string;
  internalNotes?: string | null;
  reviewedAt?: string | null;
  /**
   * Publishing automatically approves this event. Choose Rejected to keep a submission off the website.
   */
  reviewStatus: 'pending' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Upload images only, up to 5 MB each. Add useful alt text so everyone can understand the image.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image’s useful content in a short sentence. For a portrait, include the person’s name; for a logo, use the organisation’s name. Avoid filenames or ‘image of’.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    'admin-preview'?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Create and update committee profiles step by step. Changes appear on the website when you Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committee".
 */
export interface Committee {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * Full name, e.g. "Monash University". Optional.
   */
  university?: string | null;
  /**
   * Degree or course name, e.g. "Bachelor of Commerce". Optional.
   */
  course?: string | null;
  /**
   * Committee position, e.g. "President".
   */
  role: string;
  /**
   * Controls the department section on the public committee page. Use Unassigned only while reviewing legacy records.
   */
  department: 'chairs' | 'secretariat' | 'treasury' | 'amplifies' | 'careers' | 'cares' | 'unites' | 'unassigned';
  /**
   * Committee term, e.g. "2026/2027" — drives the year tabs on the page.
   */
  year: string;
  /**
   * Choose an existing portrait or upload an image up to 5 MB. Include the member’s name in its alt text.
   */
  portrait: number | Media;
  /**
   * Shown in the expanded modal on the committee page. Optional — the modal simply omits it when empty.
   */
  bio?: string | null;
  linkedin_url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Update sponsor details and logos in one page. Changes appear on the homepage when you Save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: number;
  /**
   * Sponsor name — doubles as the logo's alt text.
   */
  name: string;
  /**
   * When they came on board — newest sponsors lead the marquee.
   */
  date: string;
  /**
   * Choose an existing logo or upload an image up to 5 MB. A transparent background works best.
   */
  logo: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'committee';
        value: number | Committee;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: number | Sponsor;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  type?: T;
  industry?: T;
  companyWebsite?: T;
  logoUrl?: T;
  country?: T;
  state?: T;
  city?: T;
  workMode?: T;
  international?: T;
  studyLevels?: T;
  eligibility?: T;
  applyUrl?: T;
  closes?: T;
  added?: T;
  pay?: T;
  description?: T;
  tags?: T;
  featured?: T;
  slug?: T;
  internalNotes?: T;
  sourceKey?: T;
  lifecycle?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-lifecycle_select".
 */
export interface CareerLifecycleSelect<T extends boolean = true> {
  career?: T;
  status?: T;
  closedAt?: T;
  archivedAt?: T;
  changedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations_select".
 */
export interface OrganisationsSelect<T extends boolean = true> {
  name?: T;
  abbreviation?: T;
  university?: T;
  state?: T;
  aliases?: T;
  listed?: T;
  sourceURL?: T;
  sourceCheckedAt?: T;
  verificationNotes?: T;
  directoryKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-lifecycle_select".
 */
export interface EventLifecycleSelect<T extends boolean = true> {
  event?: T;
  status?: T;
  completedAt?: T;
  archivedAt?: T;
  changedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        'admin-preview'?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committee_select".
 */
export interface CommitteeSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  university?: T;
  course?: T;
  role?: T;
  department?: T;
  year?: T;
  portrait?: T;
  bio?: T;
  linkedin_url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  name?: T;
  date?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  lifecycle?: T;
  title?: T;
  organisation?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  venue?: T;
  streetAddress?: T;
  venueDetails?: T;
  state?: T;
  ticketURL?: T;
  poster?: T;
  contactName?: T;
  contactEmail?: T;
  internalNotes?: T;
  reviewedAt?: T;
  reviewStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}