// @vitest-environment jsdom
import {fireEvent,render,screen,cleanup,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {ListingTools} from '../components/admin/ListingTools';
const h=vi.hoisted(()=>({modified:false,canSave:true,push:vi.fn()}));
vi.mock('next/navigation',()=>({useRouter:()=>({push:h.push})}));
vi.mock('@payloadcms/ui',()=>({useDocumentInfo:()=>({id:1,hasSavePermission:h.canSave,data:{submittedForReview:true}}),useFormModified:()=>h.modified,useForm:()=>({getData:()=>({title:'Sample role',company:'Example company',applyUrl:'https://example.com/apply',description:'Public description',internalNotes:'Secret note',contactEmail:'private@example.com'})})}));
beforeEach(()=>{h.modified=false;h.canSave=true;HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};});
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
it('previews unsaved content without exposing private notes or making a request',()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);render(<ListingTools collection="careers" review/>);fireEvent.click(screen.getByRole('button',{name:'Preview'}));const frame=screen.getByTitle('Public website careers preview') as HTMLIFrameElement;const send=vi.spyOn(frame.contentWindow!,'postMessage');window.dispatchEvent(new MessageEvent('message',{origin:window.location.origin,source:frame.contentWindow,data:{type:'masca-preview-ready'}}));expect(send).toHaveBeenCalledWith(expect.objectContaining({type:'masca-career-preview',job:expect.objectContaining({title:'Sample role'})}),window.location.origin);expect(JSON.stringify(send.mock.calls)).not.toContain('Secret note');expect(JSON.stringify(send.mock.calls)).not.toContain('private@example.com');expect(screen.getByRole('dialog').textContent).not.toContain('Secret note');expect(screen.getByRole('dialog').textContent).not.toContain('private@example.com');expect(fetch).not.toHaveBeenCalled();});
it('offers no duplication action to a read-only account',()=>{h.canSave=false;render(<ListingTools collection="events"/>);expect(screen.queryByText('Duplicate as draft')).toBeNull();});
it('requires saved edits before requesting changes',()=>{h.modified=true;render(<ListingTools collection="events" review/>);expect((screen.getByRole('button',{name:'Needs changes'}) as HTMLButtonElement).disabled).toBe(true);});
it('creates a copy and opens its editor',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({id:22})}));render(<ListingTools collection="careers"/>);fireEvent.click(screen.getByLabelText('Listing actions'));fireEvent.click(screen.getByRole('button',{name:'Duplicate as draft'}));await waitFor(()=>expect(h.push).toHaveBeenCalledWith('/admin/collections/careers/22'));});
