import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";
import { Analytics } from "@vercel/analytics/next"

import { readdirSync } from "node:fs";
import { join } from "node:path";

import GsapInitializer from "@/components/GsapInitializer";
import NavBar from "@/components/NavBar";
import WalkingCrowd, { type Peep } from "@/components/WalkingCrowd";

// Auto-discover the crowd from public/casts/ (runs on the server). Drop a new
// SVG into that folder and it joins the walking crowd — no code changes needed.
function getCastPeeps(): Peep[] {
  const dir = join(process.cwd(), "public", "casts");
  return readdirSync(dir)
    .filter((file) => file.toLowerCase().endsWith(".svg"))
    .sort()
    .map((file) => ({
      name: file.replace(/\.svg$/i, ""),
      src: encodeURI(`/casts/${file}`), // encode spaces, e.g. "Jin Hong.svg"
    }));
}

// 1. Montserrat (Primary Variable Font - Split into Roman and Italic files)
const montserrat = localFont({
  src: [
    {
      path: "./fonts/Montserrat-VariableFont_wght.ttf",
      style: "normal",
    },
    {
      path: "./fonts/Montserrat-Italic-VariableFont_wght.ttf",
      style: "italic",
    },
  ],
  variable: "--font-montserrat",
});

// 2. Crimson Text (Secondary Font - Array of all static weight and style files)
const crimsonText = localFont({
  src: [
    {
      path: "./fonts/CrimsonText-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/CrimsonText-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/CrimsonText-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/CrimsonText-SemiBoldItalic.ttf",
      weight: "600",
      style: "italic",
    },
    {
      path: "./fonts/CrimsonText-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/CrimsonText-BoldItalic.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-crimson",
});

// 3. Brusher (Accent Script Font)
const brusher = localFont({
  src: "./fonts/Brusher.ttf",
  variable: "--font-brusher",
});

export const metadata: Metadata = {
  title: "MASCA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const peeps = getCastPeeps();

  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${crimsonText.variable} ${brusher.variable} antialiased`}
    >
      <body>
        <GsapInitializer />
        <NavBar />
        {children}
        <Analytics/>
        <WalkingCrowd peeps={peeps} />
      </body>
    </html>
  );
}
