'use client';
import {useEffect,useRef,useState} from 'react';
import {Upload,ImageIcon,X} from 'lucide-react';
import {MAX_POSTER_SIZE} from '@/features/events/eventSubmission';
export function PosterUpload({error}:{error?:string}) {
 const [file,setFile]=useState<File|null>(null);const [preview,setPreview]=useState('');const input=useRef<HTMLInputElement>(null);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 useEffect(()=>{const form=input.current?.form;const reset=()=>{setFile(null);setPreview('');input.current?.setCustomValidity('');};form?.addEventListener('reset',reset);return()=>form?.removeEventListener('reset',reset);},[]);
 return <div><label htmlFor="event-poster" className="text-body-sm font-bold text-gray-700">Event poster</label><div className="mt-2 rounded-xl border-2 border-dashed border-blue-100 bg-blue-50 p-5"><div className="flex flex-wrap items-center gap-4">{preview?<img src={preview} alt="Selected event poster preview" className="h-24 w-20 rounded-lg object-cover"/>:<ImageIcon className="text-blue-600" size={32} aria-hidden="true"/>}<div className="min-w-0 flex-1"><p className="break-words text-body-sm font-bold text-blue-600">{file?.name||'Choose an event poster'}</p><p className="mt-1 text-body-sm text-gray-700">{file?`${(file.size/1024/1024).toFixed(1)} MB`:'Optional. JPEG, PNG or WebP up to 4 MB.'}</p></div><label htmlFor="event-poster" className="flex cursor-pointer items-center gap-2 rounded-lg bg-white px-4 py-3 text-body-sm font-bold text-blue-600"><Upload size={16}/>{file?'Replace':'Choose image'}</label>{file&&<button type="button" aria-label="Remove poster" className="rounded-lg p-3 text-blue-600" onClick={()=>{if(input.current){input.current.value='';input.current.setCustomValidity('');input.current.dispatchEvent(new Event('change',{bubbles:true}));}setFile(null);setPreview('');}}><X size={18}/></button>}</div><input ref={input} id="event-poster" name="poster" type="file" accept="image/jpeg,image/png,image/webp" className="mt-4 block w-full text-body-sm" onChange={e=>{const next=e.target.files?.[0]||null;setFile(next);setPreview(next?.type.startsWith('image/')?URL.createObjectURL(next):'');e.target.setCustomValidity(next&&next.size>MAX_POSTER_SIZE?'Choose an image under 4 MB.':'');}}/></div>{(error||(file&&file.size>MAX_POSTER_SIZE))&&<p role="alert" className="mt-2 text-body-sm text-red-600">{error||'Choose an image under 4 MB, or remove the optional poster.'}</p>}</div>;
}
